version: '3.1'

services:

  mongodbcontainer:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-username
      MONGO_INITDB_ROOT_PASSWORD: test-password
